### ISSUE TITLE
Add output parameter

### ISSUE THREAD

**Issue by grayzu** [ms-henglu/armstrong#34]
Since most use cases will require generating multiple examples for files within a single directory (swagger examples), it would streamline the process by adding an "output-path" to the parameters.

eg.
```bash
armstrong generate -path ./createComputeInstance.json -output-path ./computeInstance
```

This option should apply for all of the commands.

**Comment by ms-henglu** [comment]
Hi @grayzu ,

I got your point now, how about renaming `-output-path` to `-working-dir`? I think it makes more sense in other commands like `test` or `auto`.
